//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetReader.Service {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class NLog : global::System.Configuration.ApplicationSettingsBase {
        
        private static NLog defaultInstance = ((NLog)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NLog())));
        
        public static NLog Default {
            get {
                return defaultInstance;
            }
        }
    }
}
