// <auto-generated />
namespace BetReader.Api.Models.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IndetityUserChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndetityUserChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201705272025414_IndetityUserChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
