// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace BetReader.Api.Models.Database.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StakeAndIsLiveProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StakeAndIsLiveProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201705131919316_StakeAndIsLiveProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
